url: "https://tamochia.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
title: "tamo's blog"
title_separator: "|"
description: "For all developers who love progiamming."
author:
  email: "tamochia@gmail.com"
  github: tamochia
  twitter: tamochia

permalink: /article/:title.html

# Build settings
markdown: kramdown

# Google Analytics
google_analytics: "G-YGJYL4PPWS"

paginate: 5
paginate_path: "page:num"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  style: expanded

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .github/
  - node_modules/
  - scripts/
  - test/
  - .env
  - .vscode/
  - .DS_Store 

include: ['_pages']
